# Generated by Django 5.2.6 on 2025-09-18 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0002_products_stock"),
    ]

    operations = [
        migrations.CreateModel(
            name="Categories",
            fields=[
                ("category_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=250)),
                ("description", models.TextField()),
            ],
        ),
    ]
